### ISSUE TITLE
Setup maven project

### ISSUE THREAD

**Issue by gldiazcardenas** [JKostikiadis/MultiAxisCharts#1]
Hi, it would be awesome having a maven project with the respective pom.xml file, so we can compile this project with a different jdk.

**Comment by JKostikiadis** [comment]
I would like to kindly ask you to check if everything is fine, I just convert the entire project into a Maven Project through a plug-in of  M2Eclipse. I hope its working as expected ( I am not very familiar with Maven, to be honest )

**Comment by gldiazcardenas** [comment]
OK, no problem, if you get any trouble do not hesitate and ask

**Comment by JKostikiadis** [comment]
I am guessing everything is good and you are now able to build the project using Maven, I will keep this issue open until tomorrow in order to give you time to find any kind of problems.

**Comment by gldiazcardenas** [comment]
Thanks, this will definitively improve the project.  By the way, you should not push the .settings and .classpath files, these are IDE dependent, and not all people use eclipse, in my case I use IDEA.

**Comment by JKostikiadis** [comment]
Noted ;)
