### ISSUE TITLE
Create Java 9 branch.

### ISSUE THREAD

**Issue by gldiazcardenas** [JKostikiadis/MultiAxisCharts#2]
## Expected Behavior
The project compiles well with java 9 modularization

## Actual Behavior
The compilation fails because there are not module dependencies defined.

## Steps to Reproduce the Problem

  1. Setup JDK 9 as project compiler.
  2. Run mvn clean install.

## Specifications

  - JDK Version: 9.0
  - Platform/OS: MacOS

## Exception

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Multiple Axis Charts 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ MultiAxisCharts ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/gabriel/IdeaProjects/GLDC/Others/MultiAxisCharts/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ MultiAxisCharts ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 6 source files to /Users/gabriel/IdeaProjects/GLDC/Others/MultiAxisCharts/target/classes
[INFO] /Users/gabriel/IdeaProjects/GLDC/Others/MultiAxisCharts/src/javafx/scene/chart/MultiAxisChart.java: /Users/gabriel/IdeaProjects/GLDC/Others/MultiAxisCharts/src/javafx/scene/chart/MultiAxisChart.java uses or overrides a deprecated API.
[INFO] /Users/gabriel/IdeaProjects/GLDC/Others/MultiAxisCharts/src/javafx/scene/chart/MultiAxisChart.java: Recompile with -Xlint:deprecation for details.
[INFO] /Users/gabriel/IdeaProjects/GLDC/Others/MultiAxisCharts/src/javafx/scene/chart/MultiAxisChart.java: Some input files use unchecked or unsafe operations.
[INFO] /Users/gabriel/IdeaProjects/GLDC/Others/MultiAxisCharts/src/javafx/scene/chart/MultiAxisChart.java: Recompile with -Xlint:unchecked for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/gabriel/IdeaProjects/GLDC/Others/MultiAxisCharts/src/javafx/scene/chart/MultiAxisBarChart.java:[56,37] package com.sun.javafx.css.converters does not exist
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.742 s
[INFO] Finished at: 2018-04-09T10:12:31-07:00
[INFO] Final Memory: 15M/49M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project MultiAxisCharts: Compilation failure
[ERROR] /Users/gabriel/IdeaProjects/GLDC/Others/MultiAxisCharts/src/javafx/scene/chart/MultiAxisBarChart.java:[56,37] package com.sun.javafx.css.converters does not exist
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Process finished with exit code 1

**Comment by JKostikiadis** [comment]
Hmm, most of the ` com.sun.*` APIs are unsupported in Java 9.  Some of the imported packages was unnecessary and they have been removed but the  `com.sun.javafx.charts.Legend` is still needed so I could create my own implementation in Java 9 or we could access it using this [method](https://stackoverflow.com/questions/47262810/eclipse-java9-how-to-access-internal-javafx-packages) which i already tested. Although there is no way to access the removed package `com.sun.javafx.collections.NonIterableChange` so i will try a different implementation using the `javafx.collections.FXCollections` package.

I will need some time for that.

**Comment by gldiazcardenas** [comment]
Sure, there is not problem, you did already some progress.

**Comment by JKostikiadis** [comment]
The new Branch for Java 9 is now available please take your time and check if everything is fine. I was able to build the project with Maven and installed JDK 9. A quick solution was to just keep the classes that we need from the com.sun package and include them to our project, thus we don't actually access the com.sun package anymore.

**Comment by gldiazcardenas** [comment]
Awesome, I will take a look.
